<?php

declare(strict_types=1);

class Silverstripe6MethodChanges
{
    public const CHANGES =
    [
        'send_post_request_instead' => [
            [
                'class' => 'DNADesign\\Elemental\\Controllers\\ElementalAreaController',
                'method' => 'apiSaveForm',
                'notes' => 'send a POST request to elementForm/$ItemID instead',
            ],
        ],

        'no_replacement' => [
            [
                'class' => 'DNADesign\\Elemental\\Controllers\\ElementalAreaController',
                'method' => 'formAction',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'DNADesign\\Elemental\\Controllers\\ElementalAreaController',
                'method' => 'removeNamespacesFromFields',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'DNADesign\\Elemental\\Models\\BaseElement',
                'method' => 'updateFromFormData',
                'notes' => 'removed without equivalent functionality to replace it',
            ],

            [
                'class' => 'SilverStripe\\Admin\\LeftAndMain',
                'method' => 'Modals',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\Admin\\LeftAndMain',
                'method' => 'getSearchFilter',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\Admin\\ModalController',
                'method' => 'getController',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\Admin\\ModalController',
                'method' => 'getName',
                'notes' => 'removed without equivalent functionality to replace it',
            ],

            [
                'class' => 'SilverStripe\\AssetAdmin\\Extensions\\RemoteFileModalExtension',
                'method' => 'getFormSchema',
                'notes' => 'removed without equivalent functionality to replace it',
            ],

            [
                'class' => 'SilverStripe\\Assets\\Shortcodes\\ImageShortcodeProvider',
                'method' => 'createImageTag',
                'notes' => 'removed without equivalent functionality to replace it',
            ],

            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'PageListSidebar',
                'notes' => 'removed without equivalent functionality',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'getList',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'getQueryFilter',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSSiteTreeFilter',
                'method' => '__construct',
                'notes' => 'removed without a constructor to replace it',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSSiteTreeFilter',
                'method' => 'mapIDs',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSSiteTreeFilter',
                'method' => 'pagesIncluded',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSSiteTreeFilter',
                'method' => 'populateIDs',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\ContentController',
                'method' => 'deleteinstallfiles',
                'notes' => 'removed without equivalent functionality',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\ContentController',
                'method' => 'successfullyinstalled',
                'notes' => 'removed without equivalent functionality',
            ],

            [
                'class' => 'SilverStripe\\Control\\Controller',
                'method' => 'has_curr',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\Core\\BaseKernel',
                'method' => 'redirectToInstaller',
                'notes' => 'removed without equivalent functionality',
            ],
            [
                'class' => 'SilverStripe\\Core\\Cache\\DefaultCacheFactory',
                'method' => 'isAPCUSupported',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\Core\\Manifest\\VersionProvider',
                'method' => 'getComposerLockPath',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\Dev\\Debug',
                'method' => 'require_developer_login',
                'notes' => 'removed without equivalent functionality',
            ],
            [
                'class' => 'SilverStripe\\Dev\\DevelopmentAdmin',
                'method' => 'getRegisteredController',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\Forms\\GridField\\GridFieldDataColumns',
                'method' => 'getValueFromRelation',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\Forms\\GridField\\GridFieldFilterHeader',
                'method' => 'getThrowExceptionOnBadDataType',
                'notes' => 'removed without equivalent functionality',
            ],
            [
                'class' => 'SilverStripe\\Forms\\GridField\\GridFieldFilterHeader',
                'method' => 'setThrowExceptionOnBadDataType',
                'notes' => 'removed without equivalent functionality',
            ],
            [
                'class' => 'SilverStripe\\Forms\\GridField\\GridFieldPaginator',
                'method' => 'getThrowExceptionOnBadDataType',
                'notes' => 'removed without equivalent functionality',
            ],
            [
                'class' => 'SilverStripe\\Forms\\GridField\\GridFieldPaginator',
                'method' => 'setThrowExceptionOnBadDataType',
                'notes' => 'removed without equivalent functionality',
            ],
            [
                'class' => 'SilverStripe\\Forms\\GridField\\GridFieldSortableHeader',
                'method' => 'getThrowExceptionOnBadDataType',
                'notes' => 'removed without equivalent functionality',
            ],
            [
                'class' => 'SilverStripe\\Forms\\GridField\\GridFieldSortableHeader',
                'method' => 'setThrowExceptionOnBadDataType',
                'notes' => 'removed without equivalent functionality',
            ],
            [
                'class' => 'SilverStripe\\ORM\\DataObject',
                'method' => 'disable_subclass_access',
                'notes' => 'removed without equivalent functionality',
            ],
            [
                'class' => 'SilverStripe\\ORM\\DataObject',
                'method' => 'enable_subclass_access',
                'notes' => 'removed without equivalent functionality',
            ],
            [
                'class' => 'SilverStripe\\ORM\\FieldType\\DBInt',
                'method' => 'Times',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\Security\\RememberLoginHash',
                'method' => 'renew',
                'notes' => 'removed without equivalent functionality',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'chooseTemplate',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'exists',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'getTemplateFileByType',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'setTemplateFile',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'templates',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'topLevel',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\View\\ThemeResourceLoader',
                'method' => 'findTemplate',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\i18n\\Messages\\Symfony\\FlushInvalidatedResource',
                'method' => 'getResource',
                'notes' => 'removed without equivalent functionality to replace it',
            ],

            [
                'class' => 'SilverStripe\\Subsites\\Controller\\SubsiteXHRController',
                'method' => 'canAccess',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\Subsites\\Extensions\\LeftAndMainSubsites',
                'method' => 'ListSubsites',
                'notes' => 'removed without equivalent functionality to replace it',
            ],
            [
                'class' => 'SilverStripe\\Subsites\\Model\\Subsite',
                'method' => 'getMembersByPermission',
                'notes' => 'removed without equivalent functionality',
            ],

            [
                'class' => 'SilverStripe\\Versioned\\Versioned',
                'method' => 'extendCanArchive',
                'notes' => 'removed without equivalent functionality',
            ],
        ],

        'rename_to' => [
            [
                'class' => 'DNADesign\\Elemental\\Extensions\\ElementalPageExtension',
                'method' => 'MetaTags',
                'notes' => 'renamed to updateMetaTags()',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'PageList',
                'notes' => 'renamed to RecordList',
            ],
            [
                'class' => 'SilverStripe\\ORM\\CMSPreviewable',
                'method' => 'CMSEditLink',
                'notes' => 'renamed to getCMSEditLink()',
            ],
            [
                'class' => 'SilverStripe\\ORM\\Hierarchy\\Hierarchy',
                'method' => 'flushCache',
                'notes' => 'renamed to onFlushCache()',
            ],
            [
                'class' => 'SilverStripe\\Security\\InheritedPermissionFlusher',
                'method' => 'flushCache',
                'notes' => 'renamed to onFlushCache()',
            ],
            [
                'class' => 'SilverStripe\\MFA\\Extension\\MemberExtension',
                'method' => 'afterMemberLoggedIn',
                'notes' => 'renamed to onAfterMemberLoggedIn()',
            ],
            [
                'class' => 'SilverStripe\\MFA\\Extension\\RequirementsExtension',
                'method' => 'init',
                'notes' => 'renamed to onInit()',
            ],
            [
                'class' => 'SilverStripe\\SessionManager\\Extensions\\RememberLoginHashExtension',
                'method' => 'onAfterRenewToken',
                'notes' => 'renamed to onAfterRenewSession()',
            ],
            [
                'class' => 'SilverStripe\\Subsites\\Extensions\\SiteTreeSubsites',
                'method' => 'MetaTags',
                'notes' => 'renamed to updateMetaTags()',
            ],
            [
                'class' => 'SilverStripe\\Versioned\\Versioned',
                'method' => 'flushCache',
                'notes' => 'renamed to onFlushCache()',
            ],
            [
                'class' => 'TractorCow\\Fluent\\Extension\\FluentLeftAndMainExtension',
                'method' => 'init',
                'notes' => 'renamed to onInit()',
            ],
            [
                'class' => 'TractorCow\\Fluent\\Extension\\FluentSiteTreeExtension',
                'method' => 'MetaTags',
                'notes' => 'renamed to updateMetaTags()',
            ],
            [
                'class' => 'TractorCow\\Fluent\\Extension\\FluentVersionedExtension',
                'method' => 'flushCache',
                'notes' => 'renamed to onFlushCache()',
            ],
        ],

        'use_instead' => [
            [
                'class' => 'DNADesign\\Elemental\\Models\\BaseElement',
                'method' => 'getDescription',
                'notes' => 'use i18n_classDescription() instead.',
            ],

            [
                'class' => 'SilverStripe\\Admin\\LeftAndMain',
                'method' => 'currentPage',
                'notes' => 'use currentRecord() instead.',
            ],
            [
                'class' => 'SilverStripe\\Admin\\LeftAndMain',
                'method' => 'currentPageID',
                'notes' => 'use currentRecordID() instead.',
            ],
            [
                'class' => 'SilverStripe\\Admin\\LeftAndMain',
                'method' => 'isCurrentPage',
                'notes' => 'use isCurrentRecord() instead.',
            ],
            [
                'class' => 'SilverStripe\\Admin\\LeftAndMain',
                'method' => 'setCurrentPageID',
                'notes' => 'use setCurrentRecordID() instead.',
            ],

            [
                'class' => 'SilverStripe\\AssetAdmin\\Extensions\\RemoteFileModalExtension',
                'method' => 'getRequest',
                'notes' => 'use $this->getOwner()->getRequest() instead.',
            ],

            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'CanOrganiseSitetree',
                'notes' => 'use canOrganiseTree instead.',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'LinkPageAdd',
                'notes' => 'use LinkRecordAdd() instead.',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'LinkPageEdit',
                'notes' => 'use LinkRecordEdit() instead.',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'LinkPageHistory',
                'notes' => 'use LinkRecordHistory() instead.',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'LinkPageSettings',
                'notes' => 'use LinkRecordSettings() instead.',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'LinkPages',
                'notes' => 'use LinkRecords instead',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'LinkPagesWithSearch',
                'notes' => 'use LinkRecordsWithSearch instead',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'PageTypes',
                'notes' => 'use RecordTypes() instead.',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'SiteTreeAsUL',
                'notes' => 'use TreeAsUL() instead.',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'SiteTreeHints',
                'notes' => 'use TreeHints() instead.',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'getPageTypes',
                'notes' => 'use getRecordTypes() instead.',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'getSiteTreeFor',
                'notes' => 'use getTreeFor() instead.',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'performPublish',
                'notes' => 'use RecursivePublishable::publishRecursive() instead.',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\ContentController',
                'method' => 'Menu',
                'notes' => 'use getMenu() instead. You can continue to use $Menu in templates.',
            ],

            [
                'class' => 'SilverStripe\\Dev\\Deprecation',
                'method' => 'withNoReplacement',
                'notes' => 'use withSuppressedNotice() instead',
            ],
            [
                'class' => 'SilverStripe\\Dev\\DevelopmentAdmin',
                'method' => 'get_links',
                'notes' => 'use getLinks() instead to include permission checks',
            ],
            [
                'class' => 'SilverStripe\\Forms\\Form',
                'method' => 'validationResult',
                'notes' => 'use validate() instead',
            ],
            [
                'class' => 'SilverStripe\\Forms\\FormField',
                'method' => 'extendValidationResult',
                'notes' => 'use extend() directly instead',
            ],
            [
                'class' => 'SilverStripe\\Security\\InheritedPermissions',
                'method' => 'getJoinTable',
                'notes' => 'use getGroupJoinTable() instead',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'get_base_tag',
                'notes' => 'use getBaseTag() instead',
            ],

            [
                'class' => 'SilverStripe\\StaticPublishQueue\\Extension\\Engine\\SiteTreePublishingEngine',
                'method' => 'getToDelete',
                'notes' => 'use getUrlsToDelete() instead',
            ],
            [
                'class' => 'SilverStripe\\StaticPublishQueue\\Extension\\Engine\\SiteTreePublishingEngine',
                'method' => 'getToUpdate',
                'notes' => 'use getUrlsToUpdate() instead',
            ],
            [
                'class' => 'SilverStripe\\StaticPublishQueue\\Extension\\Engine\\SiteTreePublishingEngine',
                'method' => 'setToDelete',
                'notes' => 'use setUrlsToDelete() instead',
            ],
            [
                'class' => 'SilverStripe\\StaticPublishQueue\\Extension\\Engine\\SiteTreePublishingEngine',
                'method' => 'setToUpdate',
                'notes' => 'use setUrlsToUpdate() instead',
            ],

            [
                'class' => 'SilverStripe\\VendorPlugin\\Methods\\CopyMethod',
                'method' => 'copy',
                'notes' => 'use Filesystem::copy instead',
            ],

            [
                'class' => 'SilverStripe\\Versioned\\Versioned',
                'method' => 'canArchive',
                'notes' => 'use canDelete() instead.',
            ],

            [
                'class' => 'Symbiote\\QueuedJobs\\Tasks\\ProcessJobQueueTask',
                'method' => 'getQueue',
                'notes' => 'use AbstractQueuedJob::getQueue() instead',
            ],
        ],

        'replace_with' => [
            [
                'class' => 'DNADesign\\Elemental\\Models\\BaseElement',
                'method' => 'getGraphQLTypeName',
                'notes' => 'replaced with getTypeName()',
            ],

            [
                'class' => 'SilverStripe\\Admin\\CMSEditLinkExtension',
                'method' => 'CMSEditLink',
                'notes' => 'replaced with DataObject::getCMSEditLink() and updateCMSEditLink()',
            ],
            [
                'class' => 'SilverStripe\\Admin\\LeftAndMain',
                'method' => 'methodSchema',
                'notes' => 'replaced with FormSchemaController::schema()',
            ],
            [
                'class' => 'SilverStripe\\Admin\\ModalController',
                'method' => 'EditorEmailLink',
                'notes' => 'replaced with linkModalForm()',
            ],
            [
                'class' => 'SilverStripe\\Admin\\ModalController',
                'method' => 'EditorExternalLink',
                'notes' => 'replaced with linkModalForm()',
            ],

            [
                'class' => 'SilverStripe\\AssetAdmin\\Extensions\\RemoteFileModalExtension',
                'method' => 'getSchemaResponse',
                'notes' => 'replaced with $this->getOwner()->getSchemaResponse() instead',
            ],

            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'getSearchContext',
                'notes' => 'replaced with SiteTree::getDefaultSearchContext()',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSMain',
                'method' => 'getSearchFieldSchema',
                'notes' => 'replaced with SearchContextForm::getSchemaData()',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSSiteTreeFilter',
                'method' => 'applyDefaultFilters',
                'notes' => 'replaced with a SearchContext subclass',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Model\\SiteTree',
                'method' => 'creatableChildPages',
                'notes' => 'replaced with CMSMain::getCreatableSubClasses()',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Model\\SiteTree',
                'method' => 'generateChildrenCacheKey',
                'notes' => 'replaced with CMSMain::generateChildrenCacheKey()',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Model\\SiteTree',
                'method' => 'getCreatableChildrenCache',
                'notes' => 'replaced with CMSMain::getCreatableChildrenCache()',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Model\\SiteTree',
                'method' => 'getIconClass',
                'notes' => 'replaced with CMSMain::getRecordIconCssClass()',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Model\\SiteTree',
                'method' => 'getPageIconURL',
                'notes' => 'replaced with CMSMain::getRecordIconUrl()',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Model\\SiteTree',
                'method' => 'page_type_classes',
                'notes' => 'replaced with updateAllowedSubClasses()',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Model\\SiteTree',
                'method' => 'setCreatableChildrenCache',
                'notes' => 'replaced with CMSMain::setCreatableChildrenCache()',
            ],

            [
                'class' => 'SilverStripe\\Dev\\DevelopmentAdmin',
                'method' => 'buildDefaults',
                'notes' => 'replaced with SilverStripe\\Dev\\Commands\\DbDefaults',
            ],
            [
                'class' => 'SilverStripe\\Dev\\DevelopmentAdmin',
                'method' => 'generatesecuretoken',
                'notes' => 'replaced with SilverStripe\\Dev\\Commands\\GenerateSecureToken',
            ],
            [
                'class' => 'SilverStripe\\Dev\\DevelopmentAdmin',
                'method' => 'runRegisteredController',
                'notes' => 'replaced with runRegisteredAction()',
            ],

            [
                'class' => 'SilverStripe\\Dev\\Tasks\\CleanupTestDatabasesTask',
                'method' => 'canView',
                'notes' => 'replaced with canRunInBrowser()',
            ],

            [
                'class' => 'SilverStripe\\Forms\\FormField',
                'method' => 'Value',
                'notes' => 'replaced by getFormattedValue() and getValue()',
            ],

            [
                'class' => 'SilverStripe\\Forms\\HTMLEditor\\HTMLEditorSanitiser',
                'method' => 'addValidElements',
                'notes' => 'replaced with HTMLEditorRuleSet',
            ],
            [
                'class' => 'SilverStripe\\Forms\\HTMLEditor\\HTMLEditorSanitiser',
                'method' => 'attributeMatchesRule',
                'notes' => 'replaced with HTMLEditorElementRule::isAttributeAllowed()',
            ],
            [
                'class' => 'SilverStripe\\Forms\\HTMLEditor\\HTMLEditorSanitiser',
                'method' => 'elementMatchesRule',
                'notes' => 'replaced with HTMLEditorRuleSet::isElementAllowed()',
            ],
            [
                'class' => 'SilverStripe\\Forms\\HTMLEditor\\HTMLEditorSanitiser',
                'method' => 'getRuleForAttribute',
                'notes' => 'replaced with logic in HTMLEditorElementRule',
            ],
            [
                'class' => 'SilverStripe\\Forms\\HTMLEditor\\HTMLEditorSanitiser',
                'method' => 'getRuleForElement',
                'notes' => 'replaced with HTMLEditorRuleSet::getRuleForElement()',
            ],
            [
                'class' => 'SilverStripe\\Forms\\HTMLEditor\\HTMLEditorSanitiser',
                'method' => 'patternToRegex',
                'notes' => 'replaced with HTMLEditorRuleSet::patternToRegex()',
            ],

            [
                'class' => 'SilverStripe\\Forms\\HTMLReadonlyField',
                'method' => 'ValueEntities',
                'notes' => 'replaced by getFormattedValueEntities()',
            ],
            [
                'class' => 'SilverStripe\\Forms\\TextareaField',
                'method' => 'ValueEntities',
                'notes' => 'replaced by getFormattedValueEntities()',
            ],

            [
                'class' => 'SilverStripe\\Forms\\GridField\\GridFieldFilterHeader',
                'method' => 'getSearchFieldSchema',
                'notes' => 'replaced with SearchContextForm::getSchemaData()',
            ],
            [
                'class' => 'SilverStripe\\Forms\\GridField\\GridFieldFilterHeader',
                'method' => 'getSearchFormSchema',
                'notes' => 'replaced with FormRequestHandler::getSchema()',
            ],

            [
                'class' => 'SilverStripe\\ORM\\PolymorphicHasManyList',
                'method' => 'setForeignRelation',
                'notes' => 'replaced with a parameter in the constructor',
            ],

            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'execute_string',
                'notes' => 'replaced with SSTemplateEngine::renderString()',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'execute_template',
                'notes' => 'replaced with SSTemplateEngine::execute_template()',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'flush_cacheblock_cache',
                'notes' => 'replaced with SSTemplateEngine::flushCacheBlockCache()',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'flush_template_cache',
                'notes' => 'replaced with SSTemplateEngine::flushTemplateCache()',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'fromString',
                'notes' => 'replaced with SSTemplateEngine::renderString()',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'getParser',
                'notes' => 'replaced with SSTemplateEngine::getParser()',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'getPartialCacheStore',
                'notes' => 'replaced with SSTemplateEngine::getPartialCacheStore()',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'getSubtemplateFor',
                'notes' => 'replaced with SSTemplateEngine::getSubtemplateFor()',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'hasTemplate',
                'notes' => 'replaced with SSTemplateEngine::hasTemplate()',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'includeGeneratedTemplate',
                'notes' => 'replaced with SSTemplateEngine::includeGeneratedTemplate()',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'parseTemplateContent',
                'notes' => 'replaced with SSTemplateEngine::parseTemplateContent()',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'setParser',
                'notes' => 'replaced with SSTemplateEngine::setParser()',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'setPartialCacheStore',
                'notes' => 'replaced with SSTemplateEngine::setPartialCacheStore()',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'setTemplate',
                'notes' => 'replaced with SSTemplateEngine::setTemplate()',
            ],

            [
                'class' => 'SilverStripe\\LinkField\\Tasks\\MigrationTaskTrait',
                'method' => 'run',
                'notes' => 'replaced with execute()',
            ],

            [
                'class' => 'SilverStripe\\SiteConfig\\SiteConfigLeftAndMain',
                'method' => 'save_siteconfig',
                'notes' => 'replaced with save()',
            ],

            [
                'class' => 'SilverStripe\\Versioned\\VersionedGridFieldItemRequest',
                'method' => 'getRecordStatus',
                'notes' => 'replaced with Versioned::updateStatusFlags()',
            ],

            [
                'class' => 'SilverStripe\\UserForms\\Model\\EditableFormField',
                'method' => 'getCMSValidator',
                'notes' => 'replaced with getCMSCompositeValidator()',
            ],
            [
                'class' => 'SilverStripe\\UserForms\\UserForm',
                'method' => 'getCMSValidator',
                'notes' => 'replaced with getCMSCompositeValidator()',
            ],

            [
                'class' => 'Symbiote\\AdvancedWorkflow\\Extensions\\WorkflowEmbargoExpiryExtension',
                'method' => 'getCMSValidator',
                'notes' => 'replaced with updateCMSCompositeValidator()',
            ],

            [
                'class' => 'TractorCow\\Fluent\\Extension\\FluentGridFieldExtension',
                'method' => 'updateBadge',
                'notes' => 'replaced with FluentExtension::updateStatusFlags()',
            ],
            [
                'class' => 'TractorCow\\Fluent\\Extension\\FluentLeftAndMainExtension',
                'method' => 'updateBreadcrumbs',
                'notes' => 'replaced with functionality in silverstripe/admin',
            ],
        ],

        'moved_to_extension' => [
            [
                'class' => 'SilverStripe\\AssetAdmin\\Controller\\AssetAdmin',
                'method' => 'addToCampaignForm',
                'notes' => 'will moved to AddToCampaignExtension',
            ],
            [
                'class' => 'SilverStripe\\AssetAdmin\\Controller\\AssetAdmin',
                'method' => 'addtocampaign',
                'notes' => 'will moved to AddToCampaignExtension',
            ],
            [
                'class' => 'SilverStripe\\AssetAdmin\\Controller\\AssetAdmin',
                'method' => 'getAddToCampaignForm',
                'notes' => 'will moved to AddToCampaignExtension',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSPageEditController',
                'method' => 'AddToCampaignForm',
                'notes' => 'moved to AddToCampaignExtension',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSPageEditController',
                'method' => 'addtocampaign',
                'notes' => 'moved to AddToCampaignExtension',
            ],
            [
                'class' => 'SilverStripe\\CMS\\Controllers\\CMSPageEditController',
                'method' => 'getAddToCampaignForm',
                'notes' => 'moved to AddToCampaignExtension',
            ],
        ],

        'other' => [
            [
                'class' => 'SilverStripe\\Forms\\FileUploadReceiver',
                'method' => 'Value',
                'notes' => 'Removed deprecated method SilverStripe\\Forms\\FileUploadReceiver::Value()',
            ],
            [
                'class' => 'SilverStripe\\Core\\Manifest\\VersionProvider',
                'method' => 'getComposerLock',
                'notes' => 'has been replaced by composer-runtime-api',
            ],
            [
                'class' => 'SilverStripe\\Forms\\SearchableDropdownTrait',
                'method' => 'validate',
                'notes' => 'removed in favour of the FormField::validate() method',
            ],
        ],
        'remove_parameter' => [
            [
                'class' => 'DNADesign\\Elemental\\Controllers\\ElementalAreaController',
                'method' => 'getElementForm',
                'parameter' => '$elementID',
                'notes' => 'Removed deprecated parameter $elementID in ElementalAreaController::getElementForm()',
            ],
            [
                'class' => 'DNADesign\\Elemental\\Controllers\\ElementalAreaController',
                'method' => 'elementForm',
                'parameter' => '$request',
                'notes' => 'Removed deprecated parameter $request in ElementalAreaController::elementForm()',
            ],
            [
                'class' => 'SilverStripe\\Assets\\Storage\\DBFile',
                'method' => 'validate',
                'parameter' => '$filename',
                'notes' => 'Removed deprecated parameter $filename in DBFile::validate()',
            ],
            [
                'class' => 'SilverStripe\\Assets\\Storage\\DBFile',
                'method' => 'validate',
                'parameter' => '$result',
                'notes' => 'Removed deprecated parameter $result in DBFile::validate()',
            ],
            [
                'class' => 'SilverStripe\\View\\SSViewer',
                'method' => 'process',
                'parameter' => '$inheritedScope',
                'notes' => 'Removed deprecated parameter $inheritedScope in SSViewer::process()',
            ],
            [
                'class' => 'SilverStripe\\Control\\Session',
                'method' => 'requestContainsSessionId',
                'parameter' => '$request',
                'notes' => 'Removed deprecated parameter $request in Session::requestContainsSessionId()',
            ],
            [
                'class' => 'SilverStripe\\Forms\\FormField',
                'method' => 'validate',
                'parameter' => '$validator',
                'notes' => 'Removed deprecated parameter $validator in FormField::validate()',
            ],
            [
                'class' => 'SilverStripe\\Versioned\\Versioned',
                'method' => 'Versions',
                'parameter' => '$having',
                'notes' => 'Removed deprecated parameter $having in Versioned::Versions()',
            ],

        ],
        'change_visibility' => [
            [
                'class' => 'EditFormFactory',
                'method' => 'namespaceFields',
                'from' => 'protected',
                'to' => 'public',
                'notes' => 'Changed visibility for method EditFormFactory::namespaceFields() from protected to public',
            ],
            [
                'class' => 'ElementalAreaUsedOnTableExtension',
                'method' => 'updateUsageAncestorDataObjects',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method ElementalAreaUsedOnTableExtension::updateUsageAncestorDataObjects() from public to protected',
            ],
            [
                'class' => 'ElementalAreaUsedOnTableExtension',
                'method' => 'updateUsageDataObject',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method ElementalAreaUsedOnTableExtension::updateUsageDataObject() from public to protected',
            ],
            [
                'class' => 'ElementalAreaUsedOnTableExtension',
                'method' => 'updateUsageExcludedClasses',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method ElementalAreaUsedOnTableExtension::updateUsageExcludedClasses() from public to protected',
            ],
            [
                'class' => 'ElementalPageExtension',
                'method' => 'updateAnchorsOnPage',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method ElementalPageExtension::updateAnchorsOnPage() from public to protected',
            ],
            [
                'class' => 'GridFieldAddNewMultiClassHandlerExtension',
                'method' => 'updateItemEditForm',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method GridFieldAddNewMultiClassHandlerExtension::updateItemEditForm() from public to protected',
            ],
            [
                'class' => 'GridFieldDetailFormItemRequestExtension',
                'method' => 'updateBreadcrumbs',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method GridFieldDetailFormItemRequestExtension::updateBreadcrumbs() from public to protected',
            ],
            [
                'class' => 'AdminErrorExtension',
                'method' => 'onBeforeHTTPError',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method AdminErrorExtension::onBeforeHTTPError() from public to protected',
            ],
            [
                'class' => 'GridFieldDetailFormPreviewExtension',
                'method' => 'updateItemEditForm',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method GridFieldDetailFormPreviewExtension::updateItemEditForm() from public to protected',
            ],
            [
                'class' => 'GridFieldPrintButtonExtension',
                'method' => 'updatePrintData',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method GridFieldPrintButtonExtension::updatePrintData() from public to protected',
            ],
            [
                'class' => 'LeftAndMain',
                'method' => 'getSchemaResponse',
                'from' => 'protected',
                'to' => 'public',
                'notes' => 'Changed visibility for method LeftAndMain::getSchemaResponse() from protected to public',
            ],
            [
                'class' => 'LeftAndMain',
                'method' => 'jsonError',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method LeftAndMain::jsonError() from public to protected',
            ],
            [
                'class' => 'AssetAdminFile',
                'method' => 'updateCMSEditLink',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method AssetAdminFile::updateCMSEditLink() from public to protected',
            ],
            [
                'class' => 'UsedOnTableExtension',
                'method' => 'updateUsageDataObject',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method UsedOnTableExtension::updateUsageDataObject() from public to protected',
            ],
            [
                'class' => 'UsedOnTableExtension',
                'method' => 'updateUsageExcludedClasses',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method UsedOnTableExtension::updateUsageExcludedClasses() from public to protected',
            ],
            [
                'class' => 'File',
                'method' => 'onAfterRevertToLive',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method File::onAfterRevertToLive() from public to protected',
            ],
            [
                'class' => 'File',
                'method' => 'onAfterUpload',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method File::onAfterUpload() from public to protected',
            ],
            [
                'class' => 'FileLinkTracking',
                'method' => 'augmentSyncLinkTracking',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FileLinkTracking::augmentSyncLinkTracking() from public to protected',
            ],
            [
                'class' => 'Folder',
                'method' => 'onAfterSkippedWrite',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method Folder::onAfterSkippedWrite() from public to protected',
            ],
            [
                'class' => 'BlogPost',
                'method' => 'onAfterWrite',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method BlogPost::onAfterWrite() from public to protected',
            ],
            [
                'class' => 'BlogPost',
                'method' => 'onBeforePublish',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method BlogPost::onBeforePublish() from public to protected',
            ],
            [
                'class' => 'BlogPostFilter',
                'method' => 'augmentLoadLazyFields',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method BlogPostFilter::augmentLoadLazyFields() from public to protected',
            ],
            [
                'class' => 'CMSMain',
                'method' => 'getCMSTreeTitle',
                'from' => 'protected',
                'to' => 'public',
                'notes' => 'Changed visibility for method CMSMain::getCMSTreeTitle() from protected to public',
            ],
            [
                'class' => 'LeftAndMainBatchActionsExtension',
                'method' => 'updateBatchActionsForm',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method LeftAndMainBatchActionsExtension::updateBatchActionsForm() from public to protected',
            ],
            [
                'class' => 'SiteTree',
                'method' => 'onAfterPublish',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteTree::onAfterPublish() from public to protected',
            ],
            [
                'class' => 'SiteTree',
                'method' => 'onAfterRevertToLive',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteTree::onAfterRevertToLive() from public to protected',
            ],
            [
                'class' => 'SiteTree',
                'method' => 'onBeforeDuplicate',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteTree::onBeforeDuplicate() from public to protected',
            ],
            [
                'class' => 'SiteTreeLinkTracking',
                'method' => 'augmentSyncLinkTracking',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteTreeLinkTracking::augmentSyncLinkTracking() from public to protected',
            ],
            [
                'class' => 'VirtualPage',
                'method' => 'onBeforeWrite',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method VirtualPage::onBeforeWrite() from public to protected',
            ],
            [
                'class' => 'ErrorPageControllerExtension',
                'method' => 'onBeforeHTTPError',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method ErrorPageControllerExtension::onBeforeHTTPError() from public to protected',
            ],
            [
                'class' => 'ErrorPageFileExtension',
                'method' => 'getErrorRecordFor',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method ErrorPageFileExtension::getErrorRecordFor() from public to protected',
            ],
            [
                'class' => 'DateField',
                'method' => 'internalToFrontend',
                'from' => 'protected',
                'to' => 'public',
                'notes' => 'Changed visibility for method DateField::internalToFrontend() from protected to public',
            ],
            [
                'class' => 'DevelopmentAdmin',
                'method' => 'getLinks',
                'from' => 'protected',
                'to' => 'public',
                'notes' => 'Changed visibility for method DevelopmentAdmin::getLinks() from protected to public',
            ],
            [
                'class' => 'TaskRunner',
                'method' => 'getTaskList',
                'from' => 'protected',
                'to' => 'public',
                'notes' => 'Changed visibility for method TaskRunner::getTaskList() from protected to public',
            ],
            [
                'class' => 'TimeField',
                'method' => 'internalToFrontend',
                'from' => 'protected',
                'to' => 'public',
                'notes' => 'Changed visibility for method TimeField::internalToFrontend() from protected to public',
            ],
            [
                'class' => 'ClientConfigProvider',
                'method' => 'updateClientConfig',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method ClientConfigProvider::updateClientConfig() from public to protected',
            ],
            [
                'class' => 'QueryRecorderExtension',
                'method' => 'augmentDataQueryCreation',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method QueryRecorderExtension::augmentDataQueryCreation() from public to protected',
            ],
            [
                'class' => 'TestSessionEnvironmentExtension',
                'method' => 'onAfterStartTestSession',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method TestSessionEnvironmentExtension::onAfterStartTestSession() from public to protected',
            ],
            [
                'class' => 'FluentLinkExtension',
                'method' => 'updateCMSFields',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentLinkExtension::updateCMSFields() from public to protected',
            ],
            [
                'class' => 'UsedOnTableExtension',
                'method' => 'updateUsageAncestorDataObjects',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method UsedOnTableExtension::updateUsageAncestorDataObjects() from public to protected',
            ],
            [
                'class' => 'EnablerExtension',
                'method' => 'afterCallActionHandler',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method EnablerExtension::afterCallActionHandler() from public to protected',
            ],
            [
                'class' => 'EnablerExtension',
                'method' => 'beforeCallActionHandler',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method EnablerExtension::beforeCallActionHandler() from public to protected',
            ],
            [
                'class' => 'MFAResetExtension',
                'method' => 'handleAccountReset',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method MFAResetExtension::handleAccountReset() from public to protected',
            ],
            [
                'class' => 'SiteTreeExtension',
                'method' => 'canView',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteTreeExtension::canView() from public to protected',
            ],
            [
                'class' => 'QueuedJobDescriptorExtension',
                'method' => 'onAfterBuild',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method QueuedJobDescriptorExtension::onAfterBuild() from public to protected',
            ],
            [
                'class' => 'RememberLoginHashExtension',
                'method' => 'onAfterGenerateToken',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method RememberLoginHashExtension::onAfterGenerateToken() from public to protected',
            ],
            [
                'class' => 'ShareDraftContentFileShortcodeProviderExtension',
                'method' => 'updateGrant',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method ShareDraftContentFileShortcodeProviderExtension::updateGrant() from public to protected',
            ],
            [
                'class' => 'SiteTreePublishingEngine',
                'method' => 'onAfterPublishRecursive',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteTreePublishingEngine::onAfterPublishRecursive() from public to protected',
            ],
            [
                'class' => 'SiteTreePublishingEngine',
                'method' => 'onBeforePublishRecursive',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteTreePublishingEngine::onBeforePublishRecursive() from public to protected',
            ],
            [
                'class' => 'BaseElementSubsites',
                'method' => 'updatePreviewLink',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method BaseElementSubsites::updatePreviewLink() from public to protected',
            ],
            [
                'class' => 'CMSPageAddControllerExtension',
                'method' => 'updatePageOptions',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method CMSPageAddControllerExtension::updatePageOptions() from public to protected',
            ],
            [
                'class' => 'ErrorPageSubsite',
                'method' => 'updateErrorFilename',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method ErrorPageSubsite::updateErrorFilename() from public to protected',
            ],
            [
                'class' => 'FileSubsites',
                'method' => 'cacheKeyComponent',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FileSubsites::cacheKeyComponent() from public to protected',
            ],
            [
                'class' => 'FileSubsites',
                'method' => 'onAfterUpload',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FileSubsites::onAfterUpload() from public to protected',
            ],
            [
                'class' => 'FolderFormFactoryExtension',
                'method' => 'updateFormFields',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FolderFormFactoryExtension::updateFormFields() from public to protected',
            ],
            [
                'class' => 'GroupSubsites',
                'method' => 'updateTreeTitle',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method GroupSubsites::updateTreeTitle() from public to protected',
            ],
            [
                'class' => 'HintsCacheKeyExtension',
                'method' => 'updateHintsCacheKey',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method HintsCacheKeyExtension::updateHintsCacheKey() from public to protected',
            ],
            [
                'class' => 'LeftAndMainSubsites',
                'method' => 'canAccess',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method LeftAndMainSubsites::canAccess() from public to protected',
            ],
            [
                'class' => 'LeftAndMainSubsites',
                'method' => 'onAfterSave',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method LeftAndMainSubsites::onAfterSave() from public to protected',
            ],
            [
                'class' => 'LeftAndMainSubsites',
                'method' => 'onBeforeInit',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method LeftAndMainSubsites::onBeforeInit() from public to protected',
            ],
            [
                'class' => 'LeftAndMainSubsites',
                'method' => 'updatePageOptions',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method LeftAndMainSubsites::updatePageOptions() from public to protected',
            ],
            [
                'class' => 'SiteConfigSubsites',
                'method' => 'cacheKeyComponent',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteConfigSubsites::cacheKeyComponent() from public to protected',
            ],
            [
                'class' => 'SiteTreeSubsites',
                'method' => 'alternateSiteConfig',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteTreeSubsites::alternateSiteConfig() from public to protected',
            ],
            [
                'class' => 'SiteTreeSubsites',
                'method' => 'augmentSyncLinkTracking',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteTreeSubsites::augmentSyncLinkTracking() from public to protected',
            ],
            [
                'class' => 'SiteTreeSubsites',
                'method' => 'augmentValidURLSegment',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteTreeSubsites::augmentValidURLSegment() from public to protected',
            ],
            [
                'class' => 'SiteTreeSubsites',
                'method' => 'cacheKeyComponent',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteTreeSubsites::cacheKeyComponent() from public to protected',
            ],
            [
                'class' => 'SiteTreeSubsites',
                'method' => 'canAddChildren',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteTreeSubsites::canAddChildren() from public to protected',
            ],
            [
                'class' => 'SiteTreeSubsites',
                'method' => 'canPublish',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteTreeSubsites::canPublish() from public to protected',
            ],
            [
                'class' => 'SiteTreeSubsites',
                'method' => 'onBeforeDuplicate',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteTreeSubsites::onBeforeDuplicate() from public to protected',
            ],
            [
                'class' => 'SiteTreeSubsites',
                'method' => 'updatePreviewLink',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method SiteTreeSubsites::updatePreviewLink() from public to protected',
            ],
            [
                'class' => 'UsedOnTableExtension',
                'method' => 'updateUsageAncestorDataObjects',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method UsedOnTableExtension::updateUsageAncestorDataObjects() from public to protected',
            ],
            [
                'class' => 'UsedOnTableExtension',
                'method' => 'updateUsageDataObject',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method UsedOnTableExtension::updateUsageDataObject() from public to protected',
            ],
            [
                'class' => 'UserFormFieldEditorExtension',
                'method' => 'onAfterDuplicate',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method UserFormFieldEditorExtension::onAfterDuplicate() from public to protected',
            ],
            [
                'class' => 'UserFormFieldEditorExtension',
                'method' => 'onAfterPublish',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method UserFormFieldEditorExtension::onAfterPublish() from public to protected',
            ],
            [
                'class' => 'UserFormFieldEditorExtension',
                'method' => 'onAfterRevertToLive',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method UserFormFieldEditorExtension::onAfterRevertToLive() from public to protected',
            ],
            [
                'class' => 'UserFormFieldEditorExtension',
                'method' => 'onAfterUnpublish',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method UserFormFieldEditorExtension::onAfterUnpublish() from public to protected',
            ],
            [
                'class' => 'UserFormFileExtension',
                'method' => 'updateTrackedFormUpload',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method UserFormFileExtension::updateTrackedFormUpload() from public to protected',
            ],
            [
                'class' => 'RecursivePublishable',
                'method' => 'onBeforeDuplicate',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method RecursivePublishable::onBeforeDuplicate() from public to protected',
            ],
            [
                'class' => 'RecursivePublishableHandler',
                'method' => 'onAfterSave',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method RecursivePublishableHandler::onAfterSave() from public to protected',
            ],
            [
                'class' => 'Versioned',
                'method' => 'augmentDataQueryCreation',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method Versioned::augmentDataQueryCreation() from public to protected',
            ],
            [
                'class' => 'Versioned',
                'method' => 'augmentLoadLazyFields',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method Versioned::augmentLoadLazyFields() from public to protected',
            ],
            [
                'class' => 'Versioned',
                'method' => 'cacheKeyComponent',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method Versioned::cacheKeyComponent() from public to protected',
            ],
            [
                'class' => 'Versioned',
                'method' => 'canView',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method Versioned::canView() from public to protected',
            ],
            [
                'class' => 'Versioned',
                'method' => 'onAfterSkippedWrite',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method Versioned::onAfterSkippedWrite() from public to protected',
            ],
            [
                'class' => 'Versioned',
                'method' => 'onBeforeDuplicate',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method Versioned::onBeforeDuplicate() from public to protected',
            ],
            [
                'class' => 'Versioned',
                'method' => 'onPrepopulateTreeDataCache',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method Versioned::onPrepopulateTreeDataCache() from public to protected',
            ],
            [
                'class' => 'Versioned',
                'method' => 'updateInheritableQueryParams',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method Versioned::updateInheritableQueryParams() from public to protected',
            ],
            [
                'class' => 'VersionedGridFieldArchiveExtension',
                'method' => 'updateConfig',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method VersionedGridFieldArchiveExtension::updateConfig() from public to protected',
            ],
            [
                'class' => 'VersionedGridFieldDetailForm',
                'method' => 'updateItemRequestClass',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method VersionedGridFieldDetailForm::updateItemRequestClass() from public to protected',
            ],
            [
                'class' => 'VersionedStateExtension',
                'method' => 'updateLink',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method VersionedStateExtension::updateLink() from public to protected',
            ],
            [
                'class' => 'VersionedTableDataQueryExtension',
                'method' => 'updateJoinTableName',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method VersionedTableDataQueryExtension::updateJoinTableName() from public to protected',
            ],
            [
                'class' => 'VersionedTestSessionExtension',
                'method' => 'updateGetURL',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method VersionedTestSessionExtension::updateGetURL() from public to protected',
            ],
            [
                'class' => 'VersionedTestSessionExtension',
                'method' => 'updatePostURL',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method VersionedTestSessionExtension::updatePostURL() from public to protected',
            ],
            [
                'class' => 'ArchiveRestoreAction',
                'method' => 'updateItemEditForm',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method ArchiveRestoreAction::updateItemEditForm() from public to protected',
            ],
            [
                'class' => 'UsedOnTableExtension',
                'method' => 'updateUsageExcludedClasses',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method UsedOnTableExtension::updateUsageExcludedClasses() from public to protected',
            ],
            [
                'class' => 'AdvancedWorkflowExtension',
                'method' => 'updateEditForm',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method AdvancedWorkflowExtension::updateEditForm() from public to protected',
            ],
            [
                'class' => 'AdvancedWorkflowExtension',
                'method' => 'updateItemEditForm',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method AdvancedWorkflowExtension::updateItemEditForm() from public to protected',
            ],
            [
                'class' => 'WorkflowApplicable',
                'method' => 'updateSettingsFields',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method WorkflowApplicable::updateSettingsFields() from public to protected',
            ],
            [
                'class' => 'WorkflowEmbargoExpiryExtension',
                'method' => 'onBeforeDuplicate',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method WorkflowEmbargoExpiryExtension::onBeforeDuplicate() from public to protected',
            ],
            [
                'class' => 'WorkflowEmbargoExpiryExtension',
                'method' => 'updateStatusFlags',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method WorkflowEmbargoExpiryExtension::updateStatusFlags() from public to protected',
            ],
            [
                'class' => 'GridFieldDetailFormItemRequestExtension',
                'method' => 'updateFormActions',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method GridFieldDetailFormItemRequestExtension::updateFormActions() from public to protected',
            ],
            [
                'class' => 'FluentChangesExtension',
                'method' => 'updateChangeType',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentChangesExtension::updateChangeType() from public to protected',
            ],
            [
                'class' => 'FluentDirectorExtension',
                'method' => 'updateRules',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentDirectorExtension::updateRules() from public to protected',
            ],
            [
                'class' => 'FluentExtension',
                'method' => 'cacheKeyComponent',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentExtension::cacheKeyComponent() from public to protected',
            ],
            [
                'class' => 'FluentExtension',
                'method' => 'updateLocalisationTabColumns',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentExtension::updateLocalisationTabColumns() from public to protected',
            ],
            [
                'class' => 'FluentExtension',
                'method' => 'updateLocalisationTabConfig',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentExtension::updateLocalisationTabConfig() from public to protected',
            ],
            [
                'class' => 'FluentFilteredExtension',
                'method' => 'updateLocalisationTabColumns',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentFilteredExtension::updateLocalisationTabColumns() from public to protected',
            ],
            [
                'class' => 'FluentFilteredExtension',
                'method' => 'updateLocalisationTabConfig',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentFilteredExtension::updateLocalisationTabConfig() from public to protected',
            ],
            [
                'class' => 'FluentFilteredExtension',
                'method' => 'updateStatusFlags',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentFilteredExtension::updateStatusFlags() from public to protected',
            ],
            [
                'class' => 'FluentGridFieldExtension',
                'method' => 'updateFormActions',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentGridFieldExtension::updateFormActions() from public to protected',
            ],
            [
                'class' => 'FluentIsolatedExtension',
                'method' => 'augmentDataQueryCreation',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentIsolatedExtension::augmentDataQueryCreation() from public to protected',
            ],
            [
                'class' => 'FluentMemberExtension',
                'method' => 'updateGroups',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentMemberExtension::updateGroups() from public to protected',
            ],
            [
                'class' => 'FluentObjectTrait',
                'method' => 'augmentDataQueryCreation',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentObjectTrait::augmentDataQueryCreation() from public to protected',
            ],
            [
                'class' => 'FluentObjectTrait',
                'method' => 'updateLocalisationTabColumns',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentObjectTrait::updateLocalisationTabColumns() from public to protected',
            ],
            [
                'class' => 'FluentObjectTrait',
                'method' => 'updateLocalisationTabConfig',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentObjectTrait::updateLocalisationTabConfig() from public to protected',
            ],
            [
                'class' => 'FluentReadVersionsExtension',
                'method' => 'updateList',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentReadVersionsExtension::updateList() from public to protected',
            ],
            [
                'class' => 'FluentSiteTreeExtension',
                'method' => 'updateLink',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentSiteTreeExtension::updateLink() from public to protected',
            ],
            [
                'class' => 'FluentSiteTreeExtension',
                'method' => 'updateRelativeLink',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentSiteTreeExtension::updateRelativeLink() from public to protected',
            ],
            [
                'class' => 'FluentSiteTreeExtension',
                'method' => 'updateStatusFlags',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentSiteTreeExtension::updateStatusFlags() from public to protected',
            ],
            [
                'class' => 'FluentVersionedExtension',
                'method' => 'onPrepopulateTreeDataCache',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentVersionedExtension::onPrepopulateTreeDataCache() from public to protected',
            ],
            [
                'class' => 'FluentVersionedExtension',
                'method' => 'updateGetVersionNumberByStage',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentVersionedExtension::updateGetVersionNumberByStage() from public to protected',
            ],
            [
                'class' => 'FluentVersionedExtension',
                'method' => 'updateIsArchived',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentVersionedExtension::updateIsArchived() from public to protected',
            ],
            [
                'class' => 'FluentVersionedExtension',
                'method' => 'updatePrePopulateVersionNumberCache',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentVersionedExtension::updatePrePopulateVersionNumberCache() from public to protected',
            ],
            [
                'class' => 'FluentVersionedExtension',
                'method' => 'updateStagesDiffer',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method FluentVersionedExtension::updateStagesDiffer() from public to protected',
            ],
            [
                'class' => 'UsesDeletePolicy',
                'method' => 'updateDeleteTables',
                'from' => 'public',
                'to' => 'protected',
                'notes' => 'Changed visibility for method UsesDeletePolicy::updateDeleteTables() from public to protected',
            ],
        ]
    ];
}
