<?php


declare(strict_types=1);

namespace Netwerkstatt\SilverstripeRector\ChangeLists\Silverstripe6;

use Netwerkstatt\SilverstripeRector\Interfaces\ChangeListInterface;
use Netwerkstatt\SilverstripeRector\Traits\MethodChangeHelper;

class VisibilityChanges implements ChangeListInterface
{
    use MethodChangeHelper;

    private const LIST =
    [

        [
            'c' => 'EditFormFactory',
            'm' => 'namespaceFields',
            'from' => 'protected',
            'to' => 'public',
            'n' => 'Changed visibility for method EditFormFactory::namespaceFields() from protected to public',
        ],
        [
            'c' => 'ElementalAreaUsedOnTableExtension',
            'm' => 'updateUsageAncestorDataObjects',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method ElementalAreaUsedOnTableExtension::updateUsageAncestorDataObjects() from public to protected',
        ],
        [
            'c' => 'ElementalAreaUsedOnTableExtension',
            'm' => 'updateUsageDataObject',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method ElementalAreaUsedOnTableExtension::updateUsageDataObject() from public to protected',
        ],
        [
            'c' => 'ElementalAreaUsedOnTableExtension',
            'm' => 'updateUsageExcludedClasses',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method ElementalAreaUsedOnTableExtension::updateUsageExcludedClasses() from public to protected',
        ],
        [
            'c' => 'ElementalPageExtension',
            'm' => 'updateAnchorsOnPage',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method ElementalPageExtension::updateAnchorsOnPage() from public to protected',
        ],
        [
            'c' => 'GridFieldAddNewMultiClassHandlerExtension',
            'm' => 'updateItemEditForm',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method GridFieldAddNewMultiClassHandlerExtension::updateItemEditForm() from public to protected',
        ],
        [
            'c' => 'GridFieldDetailFormItemRequestExtension',
            'm' => 'updateBreadcrumbs',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method GridFieldDetailFormItemRequestExtension::updateBreadcrumbs() from public to protected',
        ],
        [
            'c' => 'AdminErrorExtension',
            'm' => 'onBeforeHTTPError',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method AdminErrorExtension::onBeforeHTTPError() from public to protected',
        ],
        [
            'c' => 'GridFieldDetailFormPreviewExtension',
            'm' => 'updateItemEditForm',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method GridFieldDetailFormPreviewExtension::updateItemEditForm() from public to protected',
        ],
        [
            'c' => 'GridFieldPrintButtonExtension',
            'm' => 'updatePrintData',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method GridFieldPrintButtonExtension::updatePrintData() from public to protected',
        ],
        [
            'c' => 'LeftAndMain',
            'm' => 'getSchemaResponse',
            'from' => 'protected',
            'to' => 'public',
            'n' => 'Changed visibility for method LeftAndMain::getSchemaResponse() from protected to public',
        ],
        [
            'c' => 'LeftAndMain',
            'm' => 'jsonError',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method LeftAndMain::jsonError() from public to protected',
        ],
        [
            'c' => 'AssetAdminFile',
            'm' => 'updateCMSEditLink',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method AssetAdminFile::updateCMSEditLink() from public to protected',
        ],
        [
            'c' => 'UsedOnTableExtension',
            'm' => 'updateUsageDataObject',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method UsedOnTableExtension::updateUsageDataObject() from public to protected',
        ],
        [
            'c' => 'UsedOnTableExtension',
            'm' => 'updateUsageExcludedClasses',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method UsedOnTableExtension::updateUsageExcludedClasses() from public to protected',
        ],
        [
            'c' => 'File',
            'm' => 'onAfterRevertToLive',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method File::onAfterRevertToLive() from public to protected',
        ],
        [
            'c' => 'File',
            'm' => 'onAfterUpload',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method File::onAfterUpload() from public to protected',
        ],
        [
            'c' => 'FileLinkTracking',
            'm' => 'augmentSyncLinkTracking',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FileLinkTracking::augmentSyncLinkTracking() from public to protected',
        ],
        [
            'c' => 'Folder',
            'm' => 'onAfterSkippedWrite',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method Folder::onAfterSkippedWrite() from public to protected',
        ],
        [
            'c' => 'BlogPost',
            'm' => 'onAfterWrite',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method BlogPost::onAfterWrite() from public to protected',
        ],
        [
            'c' => 'BlogPost',
            'm' => 'onBeforePublish',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method BlogPost::onBeforePublish() from public to protected',
        ],
        [
            'c' => 'BlogPostFilter',
            'm' => 'augmentLoadLazyFields',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method BlogPostFilter::augmentLoadLazyFields() from public to protected',
        ],
        [
            'c' => 'CMSMain',
            'm' => 'getCMSTreeTitle',
            'from' => 'protected',
            'to' => 'public',
            'n' => 'Changed visibility for method CMSMain::getCMSTreeTitle() from protected to public',
        ],
        [
            'c' => 'LeftAndMainBatchActionsExtension',
            'm' => 'updateBatchActionsForm',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method LeftAndMainBatchActionsExtension::updateBatchActionsForm() from public to protected',
        ],
        [
            'c' => 'SiteTree',
            'm' => 'onAfterPublish',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteTree::onAfterPublish() from public to protected',
        ],
        [
            'c' => 'SiteTree',
            'm' => 'onAfterRevertToLive',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteTree::onAfterRevertToLive() from public to protected',
        ],
        [
            'c' => 'SiteTree',
            'm' => 'onBeforeDuplicate',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteTree::onBeforeDuplicate() from public to protected',
        ],
        [
            'c' => 'SiteTreeLinkTracking',
            'm' => 'augmentSyncLinkTracking',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteTreeLinkTracking::augmentSyncLinkTracking() from public to protected',
        ],
        [
            'c' => 'VirtualPage',
            'm' => 'onBeforeWrite',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method VirtualPage::onBeforeWrite() from public to protected',
        ],
        [
            'c' => 'ErrorPageControllerExtension',
            'm' => 'onBeforeHTTPError',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method ErrorPageControllerExtension::onBeforeHTTPError() from public to protected',
        ],
        [
            'c' => 'ErrorPageFileExtension',
            'm' => 'getErrorRecordFor',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method ErrorPageFileExtension::getErrorRecordFor() from public to protected',
        ],
        [
            'c' => 'DateField',
            'm' => 'internalToFrontend',
            'from' => 'protected',
            'to' => 'public',
            'n' => 'Changed visibility for method DateField::internalToFrontend() from protected to public',
        ],
        [
            'c' => 'DevelopmentAdmin',
            'm' => 'getLinks',
            'from' => 'protected',
            'to' => 'public',
            'n' => 'Changed visibility for method DevelopmentAdmin::getLinks() from protected to public',
        ],
        [
            'c' => 'TaskRunner',
            'm' => 'getTaskList',
            'from' => 'protected',
            'to' => 'public',
            'n' => 'Changed visibility for method TaskRunner::getTaskList() from protected to public',
        ],
        [
            'c' => 'TimeField',
            'm' => 'internalToFrontend',
            'from' => 'protected',
            'to' => 'public',
            'n' => 'Changed visibility for method TimeField::internalToFrontend() from protected to public',
        ],
        [
            'c' => 'ClientConfigProvider',
            'm' => 'updateClientConfig',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method ClientConfigProvider::updateClientConfig() from public to protected',
        ],
        [
            'c' => 'QueryRecorderExtension',
            'm' => 'augmentDataQueryCreation',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method QueryRecorderExtension::augmentDataQueryCreation() from public to protected',
        ],
        [
            'c' => 'TestSessionEnvironmentExtension',
            'm' => 'onAfterStartTestSession',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method TestSessionEnvironmentExtension::onAfterStartTestSession() from public to protected',
        ],
        [
            'c' => 'FluentLinkExtension',
            'm' => 'updateCMSFields',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentLinkExtension::updateCMSFields() from public to protected',
        ],
        [
            'c' => 'UsedOnTableExtension',
            'm' => 'updateUsageAncestorDataObjects',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method UsedOnTableExtension::updateUsageAncestorDataObjects() from public to protected',
        ],
        [
            'c' => 'EnablerExtension',
            'm' => 'afterCallActionHandler',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method EnablerExtension::afterCallActionHandler() from public to protected',
        ],
        [
            'c' => 'EnablerExtension',
            'm' => 'beforeCallActionHandler',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method EnablerExtension::beforeCallActionHandler() from public to protected',
        ],
        [
            'c' => 'MFAResetExtension',
            'm' => 'handleAccountReset',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method MFAResetExtension::handleAccountReset() from public to protected',
        ],
        [
            'c' => 'SiteTreeExtension',
            'm' => 'canView',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteTreeExtension::canView() from public to protected',
        ],
        [
            'c' => 'QueuedJobDescriptorExtension',
            'm' => 'onAfterBuild',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method QueuedJobDescriptorExtension::onAfterBuild() from public to protected',
        ],
        [
            'c' => 'RememberLoginHashExtension',
            'm' => 'onAfterGenerateToken',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method RememberLoginHashExtension::onAfterGenerateToken() from public to protected',
        ],
        [
            'c' => 'ShareDraftContentFileShortcodeProviderExtension',
            'm' => 'updateGrant',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method ShareDraftContentFileShortcodeProviderExtension::updateGrant() from public to protected',
        ],
        [
            'c' => 'SiteTreePublishingEngine',
            'm' => 'onAfterPublishRecursive',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteTreePublishingEngine::onAfterPublishRecursive() from public to protected',
        ],
        [
            'c' => 'SiteTreePublishingEngine',
            'm' => 'onBeforePublishRecursive',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteTreePublishingEngine::onBeforePublishRecursive() from public to protected',
        ],
        [
            'c' => 'BaseElementSubsites',
            'm' => 'updatePreviewLink',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method BaseElementSubsites::updatePreviewLink() from public to protected',
        ],
        [
            'c' => 'CMSPageAddControllerExtension',
            'm' => 'updatePageOptions',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method CMSPageAddControllerExtension::updatePageOptions() from public to protected',
        ],
        [
            'c' => 'ErrorPageSubsite',
            'm' => 'updateErrorFilename',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method ErrorPageSubsite::updateErrorFilename() from public to protected',
        ],
        [
            'c' => 'FileSubsites',
            'm' => 'cacheKeyComponent',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FileSubsites::cacheKeyComponent() from public to protected',
        ],
        [
            'c' => 'FileSubsites',
            'm' => 'onAfterUpload',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FileSubsites::onAfterUpload() from public to protected',
        ],
        [
            'c' => 'FolderFormFactoryExtension',
            'm' => 'updateFormFields',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FolderFormFactoryExtension::updateFormFields() from public to protected',
        ],
        [
            'c' => 'GroupSubsites',
            'm' => 'updateTreeTitle',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method GroupSubsites::updateTreeTitle() from public to protected',
        ],
        [
            'c' => 'HintsCacheKeyExtension',
            'm' => 'updateHintsCacheKey',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method HintsCacheKeyExtension::updateHintsCacheKey() from public to protected',
        ],
        [
            'c' => 'LeftAndMainSubsites',
            'm' => 'canAccess',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method LeftAndMainSubsites::canAccess() from public to protected',
        ],
        [
            'c' => 'LeftAndMainSubsites',
            'm' => 'onAfterSave',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method LeftAndMainSubsites::onAfterSave() from public to protected',
        ],
        [
            'c' => 'LeftAndMainSubsites',
            'm' => 'onBeforeInit',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method LeftAndMainSubsites::onBeforeInit() from public to protected',
        ],
        [
            'c' => 'LeftAndMainSubsites',
            'm' => 'updatePageOptions',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method LeftAndMainSubsites::updatePageOptions() from public to protected',
        ],
        [
            'c' => 'SiteConfigSubsites',
            'm' => 'cacheKeyComponent',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteConfigSubsites::cacheKeyComponent() from public to protected',
        ],
        [
            'c' => 'SiteTreeSubsites',
            'm' => 'alternateSiteConfig',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteTreeSubsites::alternateSiteConfig() from public to protected',
        ],
        [
            'c' => 'SiteTreeSubsites',
            'm' => 'augmentSyncLinkTracking',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteTreeSubsites::augmentSyncLinkTracking() from public to protected',
        ],
        [
            'c' => 'SiteTreeSubsites',
            'm' => 'augmentValidURLSegment',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteTreeSubsites::augmentValidURLSegment() from public to protected',
        ],
        [
            'c' => 'SiteTreeSubsites',
            'm' => 'cacheKeyComponent',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteTreeSubsites::cacheKeyComponent() from public to protected',
        ],
        [
            'c' => 'SiteTreeSubsites',
            'm' => 'canAddChildren',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteTreeSubsites::canAddChildren() from public to protected',
        ],
        [
            'c' => 'SiteTreeSubsites',
            'm' => 'canPublish',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteTreeSubsites::canPublish() from public to protected',
        ],
        [
            'c' => 'SiteTreeSubsites',
            'm' => 'onBeforeDuplicate',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteTreeSubsites::onBeforeDuplicate() from public to protected',
        ],
        [
            'c' => 'SiteTreeSubsites',
            'm' => 'updatePreviewLink',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method SiteTreeSubsites::updatePreviewLink() from public to protected',
        ],
        [
            'c' => 'UsedOnTableExtension',
            'm' => 'updateUsageAncestorDataObjects',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method UsedOnTableExtension::updateUsageAncestorDataObjects() from public to protected',
        ],
        [
            'c' => 'UsedOnTableExtension',
            'm' => 'updateUsageDataObject',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method UsedOnTableExtension::updateUsageDataObject() from public to protected',
        ],
        [
            'c' => 'UserFormFieldEditorExtension',
            'm' => 'onAfterDuplicate',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method UserFormFieldEditorExtension::onAfterDuplicate() from public to protected',
        ],
        [
            'c' => 'UserFormFieldEditorExtension',
            'm' => 'onAfterPublish',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method UserFormFieldEditorExtension::onAfterPublish() from public to protected',
        ],
        [
            'c' => 'UserFormFieldEditorExtension',
            'm' => 'onAfterRevertToLive',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method UserFormFieldEditorExtension::onAfterRevertToLive() from public to protected',
        ],
        [
            'c' => 'UserFormFieldEditorExtension',
            'm' => 'onAfterUnpublish',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method UserFormFieldEditorExtension::onAfterUnpublish() from public to protected',
        ],
        [
            'c' => 'UserFormFileExtension',
            'm' => 'updateTrackedFormUpload',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method UserFormFileExtension::updateTrackedFormUpload() from public to protected',
        ],
        [
            'c' => 'RecursivePublishable',
            'm' => 'onBeforeDuplicate',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method RecursivePublishable::onBeforeDuplicate() from public to protected',
        ],
        [
            'c' => 'RecursivePublishableHandler',
            'm' => 'onAfterSave',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method RecursivePublishableHandler::onAfterSave() from public to protected',
        ],
        [
            'c' => 'Versioned',
            'm' => 'augmentDataQueryCreation',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method Versioned::augmentDataQueryCreation() from public to protected',
        ],
        [
            'c' => 'Versioned',
            'm' => 'augmentLoadLazyFields',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method Versioned::augmentLoadLazyFields() from public to protected',
        ],
        [
            'c' => 'Versioned',
            'm' => 'cacheKeyComponent',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method Versioned::cacheKeyComponent() from public to protected',
        ],
        [
            'c' => 'Versioned',
            'm' => 'canView',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method Versioned::canView() from public to protected',
        ],
        [
            'c' => 'Versioned',
            'm' => 'onAfterSkippedWrite',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method Versioned::onAfterSkippedWrite() from public to protected',
        ],
        [
            'c' => 'Versioned',
            'm' => 'onBeforeDuplicate',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method Versioned::onBeforeDuplicate() from public to protected',
        ],
        [
            'c' => 'Versioned',
            'm' => 'onPrepopulateTreeDataCache',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method Versioned::onPrepopulateTreeDataCache() from public to protected',
        ],
        [
            'c' => 'Versioned',
            'm' => 'updateInheritableQueryParams',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method Versioned::updateInheritableQueryParams() from public to protected',
        ],
        [
            'c' => 'VersionedGridFieldArchiveExtension',
            'm' => 'updateConfig',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method VersionedGridFieldArchiveExtension::updateConfig() from public to protected',
        ],
        [
            'c' => 'VersionedGridFieldDetailForm',
            'm' => 'updateItemRequestClass',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method VersionedGridFieldDetailForm::updateItemRequestClass() from public to protected',
        ],
        [
            'c' => 'VersionedStateExtension',
            'm' => 'updateLink',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method VersionedStateExtension::updateLink() from public to protected',
        ],
        [
            'c' => 'VersionedTableDataQueryExtension',
            'm' => 'updateJoinTableName',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method VersionedTableDataQueryExtension::updateJoinTableName() from public to protected',
        ],
        [
            'c' => 'VersionedTestSessionExtension',
            'm' => 'updateGetURL',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method VersionedTestSessionExtension::updateGetURL() from public to protected',
        ],
        [
            'c' => 'VersionedTestSessionExtension',
            'm' => 'updatePostURL',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method VersionedTestSessionExtension::updatePostURL() from public to protected',
        ],
        [
            'c' => 'ArchiveRestoreAction',
            'm' => 'updateItemEditForm',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method ArchiveRestoreAction::updateItemEditForm() from public to protected',
        ],
        [
            'c' => 'UsedOnTableExtension',
            'm' => 'updateUsageExcludedClasses',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method UsedOnTableExtension::updateUsageExcludedClasses() from public to protected',
        ],
        [
            'c' => 'AdvancedWorkflowExtension',
            'm' => 'updateEditForm',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method AdvancedWorkflowExtension::updateEditForm() from public to protected',
        ],
        [
            'c' => 'AdvancedWorkflowExtension',
            'm' => 'updateItemEditForm',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method AdvancedWorkflowExtension::updateItemEditForm() from public to protected',
        ],
        [
            'c' => 'WorkflowApplicable',
            'm' => 'updateSettingsFields',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method WorkflowApplicable::updateSettingsFields() from public to protected',
        ],
        [
            'c' => 'WorkflowEmbargoExpiryExtension',
            'm' => 'onBeforeDuplicate',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method WorkflowEmbargoExpiryExtension::onBeforeDuplicate() from public to protected',
        ],
        [
            'c' => 'WorkflowEmbargoExpiryExtension',
            'm' => 'updateStatusFlags',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method WorkflowEmbargoExpiryExtension::updateStatusFlags() from public to protected',
        ],
        [
            'c' => 'GridFieldDetailFormItemRequestExtension',
            'm' => 'updateFormActions',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method GridFieldDetailFormItemRequestExtension::updateFormActions() from public to protected',
        ],
        [
            'c' => 'FluentChangesExtension',
            'm' => 'updateChangeType',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentChangesExtension::updateChangeType() from public to protected',
        ],
        [
            'c' => 'FluentDirectorExtension',
            'm' => 'updateRules',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentDirectorExtension::updateRules() from public to protected',
        ],
        [
            'c' => 'FluentExtension',
            'm' => 'cacheKeyComponent',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentExtension::cacheKeyComponent() from public to protected',
        ],
        [
            'c' => 'FluentExtension',
            'm' => 'updateLocalisationTabColumns',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentExtension::updateLocalisationTabColumns() from public to protected',
        ],
        [
            'c' => 'FluentExtension',
            'm' => 'updateLocalisationTabConfig',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentExtension::updateLocalisationTabConfig() from public to protected',
        ],
        [
            'c' => 'FluentFilteredExtension',
            'm' => 'updateLocalisationTabColumns',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentFilteredExtension::updateLocalisationTabColumns() from public to protected',
        ],
        [
            'c' => 'FluentFilteredExtension',
            'm' => 'updateLocalisationTabConfig',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentFilteredExtension::updateLocalisationTabConfig() from public to protected',
        ],
        [
            'c' => 'FluentFilteredExtension',
            'm' => 'updateStatusFlags',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentFilteredExtension::updateStatusFlags() from public to protected',
        ],
        [
            'c' => 'FluentGridFieldExtension',
            'm' => 'updateFormActions',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentGridFieldExtension::updateFormActions() from public to protected',
        ],
        [
            'c' => 'FluentIsolatedExtension',
            'm' => 'augmentDataQueryCreation',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentIsolatedExtension::augmentDataQueryCreation() from public to protected',
        ],
        [
            'c' => 'FluentMemberExtension',
            'm' => 'updateGroups',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentMemberExtension::updateGroups() from public to protected',
        ],
        [
            'c' => 'FluentObjectTrait',
            'm' => 'augmentDataQueryCreation',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentObjectTrait::augmentDataQueryCreation() from public to protected',
        ],
        [
            'c' => 'FluentObjectTrait',
            'm' => 'updateLocalisationTabColumns',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentObjectTrait::updateLocalisationTabColumns() from public to protected',
        ],
        [
            'c' => 'FluentObjectTrait',
            'm' => 'updateLocalisationTabConfig',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentObjectTrait::updateLocalisationTabConfig() from public to protected',
        ],
        [
            'c' => 'FluentReadVersionsExtension',
            'm' => 'updateList',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentReadVersionsExtension::updateList() from public to protected',
        ],
        [
            'c' => 'FluentSiteTreeExtension',
            'm' => 'updateLink',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentSiteTreeExtension::updateLink() from public to protected',
        ],
        [
            'c' => 'FluentSiteTreeExtension',
            'm' => 'updateRelativeLink',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentSiteTreeExtension::updateRelativeLink() from public to protected',
        ],
        [
            'c' => 'FluentSiteTreeExtension',
            'm' => 'updateStatusFlags',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentSiteTreeExtension::updateStatusFlags() from public to protected',
        ],
        [
            'c' => 'FluentVersionedExtension',
            'm' => 'onPrepopulateTreeDataCache',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentVersionedExtension::onPrepopulateTreeDataCache() from public to protected',
        ],
        [
            'c' => 'FluentVersionedExtension',
            'm' => 'updateGetVersionNumberByStage',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentVersionedExtension::updateGetVersionNumberByStage() from public to protected',
        ],
        [
            'c' => 'FluentVersionedExtension',
            'm' => 'updateIsArchived',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentVersionedExtension::updateIsArchived() from public to protected',
        ],
        [
            'c' => 'FluentVersionedExtension',
            'm' => 'updatePrePopulateVersionNumberCache',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentVersionedExtension::updatePrePopulateVersionNumberCache() from public to protected',
        ],
        [
            'c' => 'FluentVersionedExtension',
            'm' => 'updateStagesDiffer',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method FluentVersionedExtension::updateStagesDiffer() from public to protected',
        ],
        [
            'c' => 'UsesDeletePolicy',
            'm' => 'updateDeleteTables',
            'from' => 'public',
            'to' => 'protected',
            'n' => 'Changed visibility for method UsesDeletePolicy::updateDeleteTables() from public to protected',
        ],

    ];
}
